import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import LayoutMinimalCentered from '../components/LayoutMinimalCentered';
import { vendorService, serviceService, invoiceService, tenantService } from '../services/api';
import AddVendorModal from '../components/AddVendorModal';
import { InvoiceLayoutEngine } from '../components/InvoiceLayoutEngine';
import type { InvoiceData } from '../components/InvoiceLayoutEngine';
import DesignCustomizer from '../components/DesignCustomizer';
import type { DesignConfig } from '../types/InvoiceDesign';
import { designConfigs } from '../data/invoiceDesigns';

interface Vendor {
    _id: string;
    companyName: string;
    contactPerson?: string;
    email: string;
    phone?: string;
    address?: {
        street?: string;
        city?: string;
        state?: string;
        zip?: string;
        postalCode?: string;
    };
    taxId?: string;
    signatureUrl?: string; // Digital Signature
    paymentDetails?: {
        bankName?: string;
        accountNumber?: string;
    }
}

interface Service {
    _id: string;
    name: string;
    description: string;
    pricing: {
        amount: number;
        currency: string;
    };
}

const CreateInvoice = () => {
    const navigate = useNavigate();
    const [loading, setLoading] = useState(false);
    const [issuers, setIssuers] = useState<Vendor[]>([]);
    const [availableServices, setAvailableServices] = useState<Service[]>([]);
    const [showAddIssuer, setShowAddIssuer] = useState(false);
    const [maxDueDate, setMaxDueDate] = useState<string | null>(null);
    const [tenant, setTenant] = useState<any>(null);

    // --- Invoice State ---
    const [selectedIssuerId, setSelectedIssuerId] = useState('');
    const [issuer, setIssuer] = useState<Vendor | null>(null); // The "From" entity

    // "Bill To" (Client)
    const [clientDetails, setClientDetails] = useState({
        name: '',
        company: '',
        email: '',
        address: '',
        taxId: ''
    });

    const [invoiceNumber, setInvoiceNumber] = useState(''); // Will be auto-generated by backend usually
    const [issueDate, setIssueDate] = useState(new Date().toISOString().split('T')[0]);
    const [dueDate, setDueDate] = useState('');

    const [currency, setCurrency] = useState('USD');
    const [lineItems, setLineItems] = useState([
        { description: 'Consulting Services', quantity: 1, rate: 100, amount: 100 }
    ]);
    const [notes, setNotes] = useState('');

    // Footer Details
    const [footerDetails, setFooterDetails] = useState({
        contact: '',
        email: '',
        address: '',
        terms: 'Payment due within 30 days.',
        routingNumber: ''
    });

    // Design State
    const [selectedDesignId, setSelectedDesignId] = useState('1');
    const [designConfig, setDesignConfig] = useState<DesignConfig>(designConfigs[0]);

    // --- Fetch Data ---
    useEffect(() => {
        fetchIssuers();
        fetchServices();
        fetchTenantSettings();
    }, []);

    const fetchIssuers = async () => {
        try {
            const response = await vendorService.getAll();
            setIssuers(response.data.data.vendors);
        } catch (error) {
            console.error('Failed to fetch issuers', error);
        }
    };

    const fetchServices = async () => {
        try {
            const response = await serviceService.getAll();
            setAvailableServices(response.data.data.services);
        } catch (error) {
            console.error('Failed to fetch services', error);
        }
    };

    const fetchTenantSettings = async () => {
        try {
            const response = await tenantService.getCurrent();
            const t = response.data.data;
            setTenant(t);

            const settings = t.settings || {};

            // Auto-select tenant as default if no issuers or just convenience
            // But let's wait for user action.

            if (settings.maxDueDateDays) {
                const maxDate = new Date();
                maxDate.setDate(maxDate.getDate() + settings.maxDueDateDays);
                setMaxDueDate(maxDate.toISOString().split('T')[0]);
            }
            if (settings.defaultCurrency) setCurrency(settings.defaultCurrency);

            // Default to tenant if not selected
            if (!selectedIssuerId) {
                handleIssuerChange('tenant', t);
            }

        } catch (error) {
            console.error('Failed to fetch settings', error);
        }
    };

    // --- Handlers ---
    const handleIssuerChange = (vendorId: string, currentTenant?: any) => {
        const activeTenant = currentTenant || tenant;
        if (vendorId === 'tenant') {
            setSelectedIssuerId('tenant');
            setIssuer({
                _id: 'tenant',
                companyName: activeTenant?.companyName || 'My Company',
                contactPerson: activeTenant?.ownerEmail || '',
                email: activeTenant?.ownerEmail || '',
                phone: activeTenant?.branding?.phone || '',
                address: activeTenant?.branding?.companyAddress,
                taxId: activeTenant?.taxId || activeTenant?.companySettings?.taxNumber,
                signatureUrl: activeTenant?.branding?.signatureUrl,
                paymentDetails: activeTenant?.paymentDetails
            });
            // Update footer with company details as requested
            setFooterDetails({
                contact: activeTenant?.branding?.phone || '',
                email: activeTenant?.ownerEmail || '',
                address: formatAddress(activeTenant?.branding?.companyAddress) || '',
                terms: 'Payment due within 30 days.',
                routingNumber: ''
            });

        } else {
            const selected = issuers.find(v => v._id === vendorId);
            setSelectedIssuerId(vendorId);
            setIssuer(selected || null);

            // Auto-fill footer contact details from Vendor
            if (selected) {
                setFooterDetails(prev => ({
                    ...prev,
                    contact: selected.phone || selected.contactPerson || '',
                    email: selected.email || '',
                    address: formatAddress(selected.address) || '',
                    // Terms and routingNumber might not be vendor-specific, keep previous or default
                }));
            }
        }
    };

    const handleServiceSelect = (serviceId: string) => {
        const service = availableServices.find(s => s._id === serviceId);
        if (service) {
            setLineItems([...lineItems, {
                description: service.name + (service.description ? ` - ${service.description}` : ''),
                quantity: 1,
                rate: service.pricing.amount,
                amount: service.pricing.amount
            }]);
        }
    };

    const handleLineItemChange = (index: number, field: string, value: any) => {
        const newItems: any = [...lineItems];
        newItems[index][field] = value;
        if (field === 'quantity' || field === 'rate') {
            newItems[index].amount = newItems[index].quantity * newItems[index].rate;
        }
        setLineItems(newItems);
    };

    const addItem = () => {
        setLineItems([...lineItems, { description: '', quantity: 1, rate: 0, amount: 0 }]);
    };

    const removeItem = (index: number) => {
        setLineItems(lineItems.filter((_, i) => i !== index));
    };

    const handleDueDateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selected = e.target.value;
        if (maxDueDate && selected > maxDueDate) {
            alert(`Due date cannot exceed ${maxDueDate}`);
            return;
        }
        setDueDate(selected);
    };

    // --- Calculations ---
    const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);
    const tax = subtotal * 0.1; // Example 10% tax
    const total = subtotal + tax;

    // --- Save / Send ---
    const handleSave = async (status: 'draft' | 'sent' | 'download') => {
        if (!selectedIssuerId || !clientDetails.name) {
            alert('Please select an Issuer and enter Client details.');
            return;
        }

        setLoading(true);
        try {
            const invoicePayload = {
                // vendorId is the Database ID for Issuer Profile (optional)
                vendorId: (selectedIssuerId === 'tenant' || !selectedIssuerId) ? undefined : selectedIssuerId,
                // vendorSnapshot is the ISSUER details (From)
                vendorSnapshot: issuer,
                items: lineItems.map(item => ({
                    ...item,
                    taxable: true,
                    taxRate: 10
                })),
                issueDate,
                dueDate,
                currency,
                notes,
                // clientNotes is the actual CLIENT details (To)
                clientNotes: JSON.stringify(clientDetails),
                internalNotes: JSON.stringify(footerDetails),
                status: status === 'sent' ? 'sent' : 'draft',
                templateId: selectedDesignId
            };

            const response = await invoiceService.create(invoicePayload);
            const newInvoice = response.data.data;
            const newInvoiceId = newInvoice._id;

            if (status === 'sent') {
                await invoiceService.sendEmail(newInvoiceId, {
                    templateId: selectedDesignId
                });
                alert('Invoice saved and sent successfully!');
                navigate('/invoices');
            } else if (status === 'download') {
                const downloadRes = await invoiceService.downloadPDF(newInvoiceId);
                const url = window.URL.createObjectURL(new Blob([downloadRes.data]));
                const link = document.createElement('a');
                link.href = url;
                link.setAttribute('download', `Invoice-${newInvoice.invoiceNumber}.pdf`);
                document.body.appendChild(link);
                link.click();
                link.remove();
                alert('Invoice saved and PDF download started!');
                navigate('/invoices');
            } else {
                alert('Invoice draft saved successfully!');
                navigate('/invoices');
            }
        } catch (error) {
            console.error('Failed to save invoice', error);
            alert('Failed to save invoice. See console.');
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadPDF = () => handleSave('download');

    // --- Prepare Data for Layout Engine ---
    const formatAddress = (addr: any) => {
        if (!addr) return '';
        if (typeof addr === 'string') return addr;
        return `${addr.street || ''}\n${addr.city || ''}, ${addr.state || ''} ${addr.zip || ''}`;
    };

    const invoiceData: InvoiceData = {
        id: invoiceNumber || 'INV-0001',
        date: issueDate,
        dueDate: dueDate,
        vendor: { // The ISSUER ("From")
            name: issuer?.companyName || 'Your Company',
            address: formatAddress(issuer?.address),
            email: issuer?.email || '',
            phone: issuer?.phone || '',
            signature: issuer?.signatureUrl
        },
        client: { // The CLIENT ("Bill To")
            name: clientDetails.name || 'Client Name',
            company: clientDetails.company || 'Client Company',
            address: clientDetails.address || 'Client Address',
            taxId: clientDetails.taxId
        },
        items: lineItems,
        subtotal,
        tax,
        total,
        currency,
        notes,
        footer: {
            contact: footerDetails.contact,
            email: footerDetails.email,
            address: footerDetails.address,
            terms: footerDetails.terms
        }
    };

    return (
        <LayoutMinimalCentered title="Create New Invoice">
            <div className="flex flex-col lg:flex-row gap-8 h-[calc(100vh-100px)]">

                {/* LEFT PANEL: Form Inputs */}
                <div className="w-full lg:w-[450px] overflow-y-auto pr-2 space-y-6 pb-20">

                    {/* 1. Issuer Selection (From) */}
                    <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200">
                        <div className="flex justify-between items-center mb-3">
                            <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider">From (Issuer)</h3>
                            <button
                                onClick={() => setShowAddIssuer(true)}
                                className="text-xs text-indigo-600 font-semibold hover:underline"
                            >
                                + New Profile
                            </button>
                        </div>
                        <select
                            className="w-full p-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                            value={selectedIssuerId}
                            onChange={(e) => handleIssuerChange(e.target.value)}
                        >
                            <option value="">Select Issuer Profile...</option>
                            <option value="tenant" className="font-bold">My Company (Default)</option>
                            {issuers.map(i => (
                                <option key={i._id} value={i._id}>{i.companyName}</option>
                            ))}
                        </select>
                        {issuer && (
                            <div className="mt-3 p-3 bg-slate-50 rounded-lg text-xs text-slate-500 space-y-1 border border-slate-100">
                                <p className="font-semibold text-slate-700">{issuer.companyName}</p>
                                <p>{issuer.email}</p>
                                <p className="whitespace-pre-line">{formatAddress(issuer.address)}</p>
                            </div>
                        )}
                    </div>

                    {/* 2. Client Details (To) */}
                    <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200">
                        <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-3">Bill To (Client)</h3>
                        <div className="space-y-3">
                            <input
                                placeholder="Client Company Name"
                                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:bg-white focus:border-indigo-500 transition-colors"
                                value={clientDetails.company}
                                onChange={e => setClientDetails({ ...clientDetails, company: e.target.value })}
                            />
                            <input
                                placeholder="Contact Name"
                                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:bg-white focus:border-indigo-500 transition-colors"
                                value={clientDetails.name}
                                onChange={e => setClientDetails({ ...clientDetails, name: e.target.value })}
                            />
                            <input
                                placeholder="Email Address"
                                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:bg-white focus:border-indigo-500 transition-colors"
                                value={clientDetails.email}
                                onChange={e => setClientDetails({ ...clientDetails, email: e.target.value })}
                            />
                            <textarea
                                placeholder="Billing Address"
                                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:bg-white focus:border-indigo-500 transition-colors h-20 resize-none"
                                value={clientDetails.address}
                                onChange={e => setClientDetails({ ...clientDetails, address: e.target.value })}
                            />
                        </div>
                    </div>

                    {/* 3. Invoice Details */}
                    <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200">
                        <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-3">Invoice Details</h3>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-xs font-medium text-slate-500 mb-1">Issue Date</label>
                                <input
                                    type="date"
                                    className="w-full p-2 border border-slate-300 rounded-lg text-sm"
                                    value={issueDate}
                                    onChange={e => setIssueDate(e.target.value)}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-medium text-slate-500 mb-1">Due Date</label>
                                <input
                                    type="date"
                                    className="w-full p-2 border border-slate-300 rounded-lg text-sm"
                                    value={dueDate}
                                    onChange={handleDueDateChange}
                                    max={maxDueDate || undefined}
                                />
                                {maxDueDate && <p className="text-[10px] text-orange-500 mt-1">Max allowed: {maxDueDate}</p>}
                            </div>
                        </div>
                    </div>

                    {/* 4. Line Items */}
                    <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200">
                        <div className="flex justify-between items-center mb-3">
                            <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider">Items</h3>
                            <select
                                className="text-xs border border-indigo-200 text-indigo-700 bg-indigo-50 rounded-md p-1 outline-none focus:ring-2 focus:ring-indigo-500"
                                onChange={(e) => {
                                    handleServiceSelect(e.target.value);
                                    e.target.value = ''; // reset
                                }}
                            >
                                <option value="">+ Add Standard Service</option>
                                {availableServices.map(s => (
                                    <option key={s._id} value={s._id}>{s.name} - ${s.pricing.amount}</option>
                                ))}
                            </select>
                        </div>

                        <div className="space-y-3 mb-3">
                            {lineItems.map((item, index) => (
                                <div key={index} className="flex gap-2 items-start group">
                                    <div className="flex-1">
                                        <input
                                            className="w-full p-2 border border-slate-200 rounded-md text-sm bg-slate-50 focus:bg-white transition-colors"
                                            value={item.description}
                                            onChange={(e) => handleLineItemChange(index, 'description', e.target.value)}
                                            placeholder="Description"
                                        />
                                    </div>
                                    <div className="w-16">
                                        <input
                                            type="number"
                                            className="w-full p-2 border border-slate-200 rounded-md text-sm text-right"
                                            value={item.quantity}
                                            onChange={(e) => handleLineItemChange(index, 'quantity', Number(e.target.value))}
                                        />
                                    </div>
                                    <div className="w-20">
                                        <input
                                            type="number"
                                            className="w-full p-2 border border-slate-200 rounded-md text-sm text-right"
                                            value={item.rate}
                                            onChange={(e) => handleLineItemChange(index, 'rate', Number(e.target.value))}
                                        />
                                    </div>
                                    <button
                                        onClick={() => removeItem(index)}
                                        className="mt-2 text-slate-400 hover:text-red-500 transition-colors"
                                    >
                                        &times;
                                    </button>
                                </div>
                            ))}
                        </div>

                        <button
                            onClick={addItem}
                            className="w-full py-2 border border-dashed border-slate-300 rounded-lg text-sm text-slate-500 hover:border-indigo-400 hover:text-indigo-600 transition-colors"
                        >
                            + Add Custom Line Item
                        </button>

                        <div className="mt-4 pt-4 border-t border-slate-100 flex justify-between items-center">
                            <span className="font-bold text-slate-700">Total</span>
                            <span className="text-xl font-bold text-indigo-600">{currency} {total.toFixed(2)}</span>
                        </div>
                    </div>

                    <div className="bg-white p-5 rounded-xl shadow-sm border border-slate-200">
                        <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-3">Footer Info (Company Branding)</h3>
                        <div className="grid grid-cols-2 gap-3">
                            <div>
                                <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Company Contact</label>
                                <input
                                    placeholder="Contact Phone"
                                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm"
                                    value={footerDetails.contact}
                                    onChange={e => setFooterDetails({ ...footerDetails, contact: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Company Email</label>
                                <input
                                    placeholder="email@company.com"
                                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm"
                                    value={footerDetails.email}
                                    onChange={e => setFooterDetails({ ...footerDetails, email: e.target.value })}
                                />
                            </div>
                            <div className="col-span-2">
                                <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Company Address</label>
                                <input
                                    placeholder="123 Business St, Suite 100"
                                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm"
                                    value={footerDetails.address}
                                    onChange={e => setFooterDetails({ ...footerDetails, address: e.target.value })}
                                />
                            </div>
                            <div className="col-span-2">
                                <label className="block text-[10px] uppercase font-bold text-slate-400 mb-1">Terms & Conditions</label>
                                <textarea
                                    placeholder="Payment terms, etc."
                                    className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-lg text-sm h-16 resize-none"
                                    value={footerDetails.terms}
                                    onChange={e => setFooterDetails({ ...footerDetails, terms: e.target.value })}
                                />
                            </div>
                        </div>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex gap-3 pt-2">
                        <button
                            onClick={() => handleSave('draft')}
                            disabled={loading}
                            className="flex-1 py-3 bg-white border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 font-medium transition-colors"
                        >
                            {loading ? 'Saving...' : 'Save Draft'}
                        </button>
                        <button
                            onClick={() => handleSave('sent')}
                            disabled={loading}
                            className="flex-1 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 font-medium shadow-lg shadow-indigo-200 transition-colors"
                        >
                            {loading ? 'Sending...' : 'Save & Send'}
                        </button>
                    </div>

                </div>

                {/* RIGHT PANEL: Live Preview & Customization */}
                <div className="flex-1 bg-slate-100 rounded-xl overflow-hidden border border-slate-200 shadow-inner flex flex-col">

                    {/* Toolbar */}
                    <div className="bg-white border-b border-slate-200 p-3 flex justify-between items-center z-10">
                        <div className="flex gap-2 items-center">
                            <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">Template:</div>
                            <select
                                className="text-sm border-none bg-slate-100 rounded px-2 py-1 font-medium text-slate-700 cursor-pointer hover:bg-slate-200 transition-colors outline-none"
                                value={selectedDesignId}
                                onChange={(e) => setSelectedDesignId(e.target.value)}
                            >
                                <option value="1">Executive</option>
                                <option value="2">Sidebar Console</option>
                                <option value="3">Split Vertical</option>
                                <option value="4">Thermal Receipt</option>
                                <option value="5">Swiss Grid</option>
                                <option value="6">Bottom Heavy</option>
                                <option value="7">Horizontal Strip</option>
                                <option value="8">Floating Cards</option>
                                <option value="9">Tech Terminal</option>
                                <option value="10">Magazine</option>
                                <option value="11">Monolith</option>
                                <option value="12">Classical</option>
                                <option value="13">Deep Blue</option>
                                <option value="14">Neon Night</option>
                                <option value="15">Minimalist Lines</option>
                                <option value="16">Bold Brutalism</option>
                                <option value="17">Nature Fresh</option>
                                <option value="18">Abstract Shapes</option>
                                <option value="19">Coder Dark</option>
                                <option value="20">Blueprint</option>
                            </select>
                        </div>
                        <button
                            onClick={handleDownloadPDF}
                            disabled={loading}
                            className="flex items-center gap-2 px-4 py-1.5 bg-indigo-50 text-indigo-700 rounded-lg hover:bg-indigo-100 transition-colors text-sm font-bold border border-indigo-100"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            {loading ? 'Processing...' : 'Download PDF'}
                        </button>
                    </div>

                    <div className="flex-1 overflow-y-auto relative bg-slate-50/50">
                        <div className="flex justify-center p-8 min-h-full">
                            <div className="w-[210mm] origin-top scale-[0.6] sm:scale-[0.7] md:scale-[0.8] lg:scale-[0.6] xl:scale-[0.75] 2xl:scale-[0.9] transition-transform duration-300 shadow-2xl bg-white">
                                <InvoiceLayoutEngine designId={selectedDesignId} data={invoiceData} />
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <AddVendorModal isOpen={showAddIssuer} onClose={() => setShowAddIssuer(false)} onVendorAdded={(newVendor) => {
                setIssuers([...issuers, newVendor]);
                handleIssuerChange(newVendor._id);
                setShowAddIssuer(false);
            }} />
        </LayoutMinimalCentered>
    );
};

export default CreateInvoice;
